"""update user_token table

Revision ID: 413df153d246
Revises: f9b03a569ee3
Create Date: 2025-06-29 00:16:11.063659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413df153d246'
down_revision: Union[str, None] = 'f9b03a569ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_tokens_jti'), ['jti'], unique=True)
        batch_op.drop_column('access_token')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_tokens_jti'))
        batch_op.drop_column('jti')

    # ### end Alembic commands ### 