"""Update user_tokens table

Revision ID: f9b03a569ee3
Revises: 729d7f2dace8
Create Date: 2025-06-28 16:36:47.527680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b03a569ee3'
down_revision: Union[str, None] = '729d7f2dace8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.alter_column('token_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index('ix_user_tokens_id')
        batch_op.drop_column('scope')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_index('ix_user_tokens_id', ['id'], unique=False)
        batch_op.alter_column('token_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ### 