"""update task table to include my-day and starred

Revision ID: d3a83e0e4c0e
Revises: 0d107b8b3153
Create Date: 2025-07-08 06:50:15.105832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a83e0e4c0e'
down_revision: Union[str, None] = '0d107b8b3153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_my_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('starred', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('starred')
        batch_op.drop_column('is_in_my_day')

    # ### end Alembic commands ### 